<?php
/**
 * Disaster Relief Camp & Volunteer Coordination System
 * Help Request Form Handler (submit_request.php)
 * 
 * This file handles the POST submission from index.html, validates inputs,
 * inserts data into the affected_families MySQL table, and redirects back.
 */

// Start the session to retain values if needed (for tracking sessions)
session_start();

// Include database connection
require_once 'db_connect.php';

// Check if the form was actually submitted via POST
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    
    // 1. Retrieve and sanitize input fields to prevent Cross-Site Scripting (XSS)
    // Support both 'head_name' and fallback 'full_name' for compatibility
    $head_name     = isset($_POST['head_name']) ? trim($_POST['head_name']) : (isset($_POST['full_name']) ? trim($_POST['full_name']) : '');
    $mobile        = isset($_POST['mobile']) ? trim($_POST['mobile']) : '';
    $nid_no        = isset($_POST['nid_no']) ? trim($_POST['nid_no']) : (isset($_POST['nid']) ? trim($_POST['nid']) : ''); 
    $member_count  = isset($_POST['member_count']) ? intval($_POST['member_count']) : 1;
    $address       = isset($_POST['address']) ? trim($_POST['address']) : '';
    $disaster_type = isset($_POST['disaster_type']) ? trim($_POST['disaster_type']) : '';
    $help_needed   = isset($_POST['help_needed']) ? trim($_POST['help_needed']) : '';
    $description   = isset($_POST['description']) ? trim($_POST['description']) : '';

    // 2. Perform Basic Server-side Validation
    $errors = [];

    if (empty($head_name)) {
        $errors[] = "Family Head Name is required.";
    }
    if (empty($mobile)) {
        $errors[] = "Mobile Number is required.";
    } elseif (!preg_match('/^[0-9+]{11,15}$/', $mobile)) {
        $errors[] = "Please enter a valid mobile number (11-15 digits).";
    }
    if ($member_count < 1) {
        $errors[] = "Family member count must be at least 1.";
    }
    if (empty($address)) {
        $errors[] = "Address is required.";
    }
    if (empty($disaster_type)) {
        $errors[] = "Please select a Disaster Type.";
    }
    if (empty($help_needed)) {
        $errors[] = "Please select the help needed.";
    }
    if (empty($description)) {
        $errors[] = "Description of your situation is required.";
    }

    // 3. If there are validation errors, redirect back to index.html with error parameters
    if (!empty($errors)) {
        $error_msg = implode(". ", $errors);
        header("Location: index.html?status=error&msg=" . urlencode($error_msg) . "#request-form");
        exit;
    }

    try {
        // 4. Prepare SQL query with placeholders to insert the family request safely into affected_families
        $sql = "INSERT INTO affected_families (
                    head_name, 
                    mobile, 
                    nid_no, 
                    member_count,
                    address, 
                    disaster_type, 
                    help_needed, 
                    description, 
                    status
                ) VALUES (
                    :head_name, 
                    :mobile, 
                    :nid_no, 
                    :member_count,
                    :address, 
                    :disaster_type, 
                    :help_needed, 
                    :description, 
                    'Pending'
                )";

        $stmt = $pdo->prepare($sql);

        // 5. Bind parameters to execute the query safely
        $stmt->execute([
            ':head_name'     => $head_name,
            ':mobile'        => $mobile,
            ':nid_no'        => !empty($nid_no) ? $nid_no : null, // Store as NULL if empty
            ':member_count'  => $member_count,
            ':address'       => $address,
            ':disaster_type' => $disaster_type,
            ':help_needed'   => $help_needed,
            ':description'   => $description
        ]);

        // 6. Retrieve the family_id generated by MySQL
        $new_request_id = $pdo->lastInsertId();

        // Redirect back to index.html with a success anchor and Request ID in the URL
        header("Location: index.html?status=success&id=" . $new_request_id . "#request-form");
        exit;

    } catch (PDOException $e) {
        // Handle constraint or PDO exceptions (e.g. duplicate NID)
        $msg = "Database error: " . $e->getMessage();
        if ($e->getCode() == 23000) {
            $msg = "This National ID (NID) has already registered a request.";
        }
        header("Location: index.html?status=error&msg=" . urlencode($msg) . "#request-form");
        exit;
    }

} else {
    // Redirect direct access attempts to index.html
    header("Location: index.html");
    exit;
}
?>
